name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Deploy Code to Server
      run: |
        ssh user@your-server 'cd /discordbots/quotedb/quotedb/main/ && git pull https://github.com/ReallyBadDeveloper/QuoteDB main'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
